### ISSUE TITLE
zAdd doesnt add score

### ISSUE THREAD

**Issue by hq9000** [phpredis/phpredis#1007]
today we've cloned the develop branch and noticed that zAdd supplied with some numeric values actually sets score always to 0.

After rolling back to 9114530dfcc57b382f2b5fa problem disappeared

**Comment by yatsukhnenko** [comment]
What version of php do you use? Could you provide script for testing?

**Comment by hq9000** [comment]
php -v
PHP 5.6.27 (cli) (built: Oct 15 2016 20:57:37)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

relevant piece of code is below. As you can see we use piping.


`        $affectedCatIds = array_keys($dataForRedis);

        foreach ($affectedCatIds as $categoryId) {
            $pipe = $redisClient->multi(Redis::PIPELINE);
            $key = FeaturedInOfferLogic::getTemporaryKeyForCategory($categoryId);
            foreach ($dataForRedis[$categoryId] as $element) {
                $pipe->zAdd($key, $element['score'], $element['value']);
            }
            $pipe->exec();
        }`

**Comment by yatsukhnenko** [comment]
The following code works fine from cli
```
$redis = new Redis();
$redis->connect("localhost");
$redis->multi(Redis::PIPELINE);
for ($i = 0; $i < 10; $i++) {
    $redis->zAdd("x", $i / 10; $i);
}
$redis->exec();
print_r($redis->zrange("x", 0, -1));
Array
(
    [0] => 0
    [1] => 1
    [2] => 2
    [3] => 3
    [4] => 4
    [5] => 5
    [6] => 6
    [7] => 7
    [8] => 8
    [9] => 9
)
```
redis-cli monitor shows
```
1478700472.155180 [0 [::1]:59768] "ZADD" "x" "0.0000000000000000" "0"
1478700472.155224 [0 [::1]:59768] "ZADD" "x" "0.1000000000000000" "1"
1478700472.155261 [0 [::1]:59768] "ZADD" "x" "0.2000000000000000" "2"
1478700472.155292 [0 [::1]:59768] "ZADD" "x" "0.3000000000000000" "3"
1478700472.155322 [0 [::1]:59768] "ZADD" "x" "0.4000000000000000" "4"
1478700472.155352 [0 [::1]:59768] "ZADD" "x" "0.5000000000000000" "5"
1478700472.155383 [0 [::1]:59768] "ZADD" "x" "0.6000000000000000" "6"
1478700472.155415 [0 [::1]:59768] "ZADD" "x" "0.7000000000000000" "7"
1478700472.155447 [0 [::1]:59768] "ZADD" "x" "0.8000000000000000" "8"
1478700472.155480 [0 [::1]:59768] "ZADD" "x" "0.9000000000000000" "9"
1478700472.155663 [0 [::1]:59768] "ZRANGE" "x" "0" "-1"
```

**Comment by yatsukhnenko** [comment]
@hq9000, could you try the latest commit from `develop` brunch?

**Comment by hq9000** [comment]
We've installed a new box today and again tried the latest dev (git clone https://github.com/phpredis/phpredis.git). No use - the problem persists and again we had to roll back to that old commit 9114530, which again solved the problem.

I tried the example provided above and it seemed to work fine even without the rollback.

we use centos7
PHP 5.6.27
and redis 2.8.19

**Comment by yatsukhnenko** [comment]
@hq9000 so does it works or not?

**Comment by hq9000** [comment]
no, it doesn't.

**Comment by EmreErdogan** [comment]
Similar problem here. Yesterday I downloaded the develop branch and noticed that zAdd has some weird behaviour. For example:

```
$redis->zAdd('myset', 10, "TEN");
$redis->zAdd('myset', 1, "ONE");
$redis->zAdd('myset', 7, "SEVEN");
$redis->zAdd('myset', 5, "FIVE");

$range = $redis->zRange('myset', 0, -1, true);
var_export($range);
```

The output is: 

> array (
>   'FIVE' => 0,
>   'ONE' => 0,
>   'SEVEN' => 0,
>   'TEN' => 0,
> )

**Comment by yatsukhnenko** [comment]
fixed in #1035

**Comment by yatsukhnenko** [comment]
If @michael-grunder won't approve changes from #1035 in next few days I'll create another PR especially for this issue

**Comment by yatsukhnenko** [comment]
@hq9000, @EmreErdogan, try the latest code from `develop` branch

**Comment by EmreErdogan** [comment]
@yatsukhnenko I downloaded the develop branch again and followed the installation instructions. But nothing changed. Still getting the same output. There may be something I am doing wrong. Any idea?

**Comment by hq9000** [comment]
BTW, is there something like a stable branch? I just realized that it's odd that we use something called "develop" for production.

**Comment by yatsukhnenko** [comment]
@EmreErdogan, what wersion of phpredis do you see at `phpinfo()` output?
@hq9000, you can find "stable" version of phpredis on pecl site

**Comment by EmreErdogan** [comment]
@yatsukhnenko I don't see a "phpredis" in `phpinfo()` output, but there is "Redis Version" which is 3.1.0-rc1

**Comment by yatsukhnenko** [comment]
@EmreErdogan, yep, that's it :) I pushed some changes into `develop` branch, could you test?

**Comment by EmreErdogan** [comment]
@yatsukhnenko I am still getting the same output. Scoring doesn't seem to be working. Should I remove some files before reinstalling phpredis?

**Comment by yatsukhnenko** [comment]
@EmreErdogan, I don't think you need to remove anything. make install + restart php-fpm/apache

**Comment by kobeng** [comment]
Scoring still doesn't seem to be working,i git checkout today ,the bugs still here

**Comment by yatsukhnenko** [comment]
@kobeng, what do you see in redis-cli monitor where run $redis->zAdd?

**Comment by kobeng** [comment]
Scoring still doesn't seem to be working,i am git clone today ,the bugs still here

phpinfo
redis

Redis Support => enabled
Redis Version => 3.1.0

redis-cli
20005) "s:5:"12350";"
20006) "0"

php code:

$_lottery_number = "12350";
var_dump($redis->zAdd($key, 1 , $_lottery_number));

**Comment by yatsukhnenko** [comment]
@kobeng, try to disable serializer

**Comment by kobeng** [comment]
:6379> ZRANGE rList19-2143561 0 -1 WITHSCORES
1) "12351"
2) "0"

**Comment by yatsukhnenko** [comment]
Hey, I have merged #1068. This issue should be fixed

**Comment by yatsukhnenko** [comment]
Let's assume that the problem is fixed 😀
