### ISSUE TITLE
cluster operation cause the php  coredump

### ISSUE THREAD

**Issue by zhuleilei** [phpredis/phpredis#1036]
I got two segfault error on my server

```bash
Nov 29 15:24:25 php-server kernel: php-fpm[96207] general protection ip:7e38ba sp:7fff41aefe60 error:0 in php-fpm[400000+a86000]
Nov 29 15:24:31 php-server kernel: php-fpm[96203]: segfault at 0 ip 00000000007e38ba sp 00007fff41aefe60 error 4 in php-fpm[400000+a86000]
```

With gdb  the coredump get the backtrace
```bash
Program terminated with signal 11, Segmentation fault.
#0  zend_mm_free_heap (ptr=0xc) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408

warning: Source file is more recent than executable.
1408			ZEND_MM_CHECK(chunk->heap == heap, "zend_mm_heap corrupted");
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  zend_mm_free_heap (ptr=0xc) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
#1  _efree (ptr=0xc) at /root/source/php-7.0.7/Zend/zend_alloc.c:2466
#2  0x00007f3751e73627 in cluster_check_response (c=0x7f3758bca000, reply_type=0x7f3758bee488) at /root/phpredis/cluster_library.c:1027
#3  0x00007f3751e76946 in cluster_send_command (c=0x7f3758bca000, slot=<value optimized out>, cmd=0x7f3758b4a460 "*2\r\n$3\r\nGET\r\n$32\r\ncom.juanpi.chb.tabconfig.key_zhe\r\n", cmd_len=52) at /root/phpredis/cluster_library.c:1437
#4  0x00007f3751e6d9f6 in zim_RedisCluster_get (execute_data=0x7f3758a16020, return_value=0x7fff41af0500) at /root/phpredis/redis_cluster.c:534
#5  0x00000000007fa6e8 in zend_call_function (fci=0x7fff41af0480, fci_cache=0x7fff41af04d0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#6  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7f3758a15f30) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#7  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f3758a15e40) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#8  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#9  0x0000000000899f2b in zend_execute (op_array=0x7f3758a6e000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#10 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#11 0x00000000007a9de0 in php_execute_script (primary_file=0x7fff41af2c70) at /root/source/php-7.0.7/main/main.c:2494
#12 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968





Program terminated with signal 11, Segmentation fault.
#0  zend_mm_free_heap (ptr=0xc) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408

warning: Source file is more recent than executable.
1408			ZEND_MM_CHECK(chunk->heap == heap, "zend_mm_heap corrupted");
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  zend_mm_free_heap (ptr=0x2274726f73222c22) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
#1  _efree (ptr=0x2274726f73222c22) at /root/source/php-7.0.7/Zend/zend_alloc.c:2466
#2  0x00007f3751e73627 in cluster_check_response (c=0x7f3758bca000, reply_type=0x7f3758bee488) at /root/phpredis/cluster_library.c:1027
#3  0x00007f3751e76946 in cluster_send_command (c=0x7f3758bca000, slot=<value optimized out>, cmd=0x7f3758b4a460 "*2\r\n$3\r\nGET\r\n$32\r\ncom.juanpi.chb.tabconfig.key_zhe\r\n", cmd_len=52) at /root/phpredis/cluster_library.c:1437
#4  0x00007f3751e6d9f6 in zim_RedisCluster_get (execute_data=0x7f3758a16020, return_value=0x7fff41af0500) at /root/phpredis/redis_cluster.c:534
#5  0x00000000007fa6e8 in zend_call_function (fci=0x7fff41af0480, fci_cache=0x7fff41af04d0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#6  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7f3758a15f30) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#7  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f3758a15e40) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#8  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#9  0x0000000000899f2b in zend_execute (op_array=0x7f3758a6e000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#10 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#11 0x00000000007a9de0 in php_execute_script (primary_file=0x7fff41af2c70) at /root/source/php-7.0.7/main/main.c:2494
#12 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968
```

It seems the same question.

gdb include the php's gdbinit and last debug trace was 
```
0x7f3758a16020] RedisCluster->get("com.juanpi.chb.tabconfig.key_zhe") [internal function]
```

Environment : 
PHP 7.0.7
phpredis 3.1.0-rc1  (because of the issue #971 ,i have upgrade the phpredis from 3.0.0 to the newest develop branch 3.1.0-rc1)
Centos 6.5

**Comment by yatsukhnenko** [comment]
Looks like double free

**Comment by yatsukhnenko** [comment]
@zhuleilei, try fix from PR #1037

**Comment by zhuleilei** [comment]
@yatsukhnenko  thanks,I'll try it later.

**Comment by zhuleilei** [comment]
@yatsukhnenko  not fix yet,

```bash
Program terminated with signal 11, Segmentation fault.
#0  zend_mm_free_heap (ptr=0xb) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408

warning: Source file is more recent than executable.
1408			ZEND_MM_CHECK(chunk->heap == heap, "zend_mm_heap corrupted");
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  zend_mm_free_heap (ptr=0xb) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
#1  _efree (ptr=0xb) at /root/source/php-7.0.7/Zend/zend_alloc.c:2466
#2  0x00007fe5cbac25b7 in cluster_check_response (c=0x7fe5d2737000, reply_type=0x7fe5d275b488) at /root/phpredis/cluster_library.c:1023
#3  0x00007fe5cbac5886 in cluster_send_command (c=0x7fe5d2737000, slot=<value optimized out>, cmd=0x7fe5d2604fa0 "*2\r\n$3\r\nGET\r\n$8\r\nt1324582\r\n", cmd_len=27) at /root/phpredis/cluster_library.c:1433
#4  0x00007fe5cbabc986 in zim_RedisCluster_get (execute_data=0x7fe5d2616b30, return_value=0x7ffff2c8e050) at /root/phpredis/redis_cluster.c:534
#5  0x00000000007fa6e8 in zend_call_function (fci=0x7ffff2c8dfd0, fci_cache=0x7ffff2c8e020) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#6  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7fe5d2616a40) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#7  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7fe5d2616950) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#8  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#9  0x00000000007fa678 in zend_call_function (fci=0x7ffff2c8e250, fci_cache=0x7ffff2c8e2a0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:866
#10 0x0000000000672dd9 in zim_reflection_method_invoke (execute_data=<value optimized out>, return_value=0x7fe5d26163f0) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3234
#11 0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7fe5d26162c0) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#12 0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#13 0x0000000000899f2b in zend_execute (op_array=0x7fe5d266d000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#14 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#15 0x00000000007a9de0 in php_execute_script (primary_file=0x7ffff2c90a30) at /root/source/php-7.0.7/main/main.c:2494
#16 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968
(gdb) zbacktrace 
[0x7fe5d2616b30] RedisCluster->get("t1324582") [internal function]

```

**Comment by zhuleilei** [comment]
```bash
Program terminated with signal 11, Segmentation fault.
#0  zend_mm_free_heap (ptr=0x3b787030333a7468) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408

warning: Source file is more recent than executable.
1408			ZEND_MM_CHECK(chunk->heap == heap, "zend_mm_heap corrupted");
Missing separate debuginfos, use: debuginfo-install php-7.0.7-1.el6.x86_64
(gdb) bt
#0  zend_mm_free_heap (ptr=0x3b787030333a7468) at /root/source/php-7.0.7/Zend/zend_alloc.c:1408
#1  _efree (ptr=0x3b787030333a7468) at /root/source/php-7.0.7/Zend/zend_alloc.c:2466
#2  0x00007f24c70c2867 in cluster_check_response (c=0x7f24cdd37000, reply_type=0x7f24cdd5b488) at /root/phpredis/cluster_library.c:1025
#3  0x00007f24c70c5b36 in cluster_send_command (c=0x7f24cdd37000, slot=<value optimized out>, cmd=0x7f24cdc04fa0 "*2\r\n$3\r\nGET\r\n$8\r\nt1324575\r\n", cmd_len=27) at /root/phpredis/cluster_library.c:1435
#4  0x00007f24c70bcc36 in zim_RedisCluster_get (execute_data=0x7f24cdc16b30, return_value=0x7fff5e3f17a0) at /root/phpredis/redis_cluster.c:534
#5  0x00000000007fa6e8 in zend_call_function (fci=0x7fff5e3f1720, fci_cache=0x7fff5e3f1770) at /root/source/php-7.0.7/Zend/zend_execute_API.c:885
#6  0x0000000000674811 in zim_reflection_method_invokeArgs (execute_data=<value optimized out>, return_value=0x7f24cdc16a40) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3348
#7  0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f24cdc16950) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#8  0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#9  0x00000000007fa678 in zend_call_function (fci=0x7fff5e3f19a0, fci_cache=0x7fff5e3f19f0) at /root/source/php-7.0.7/Zend/zend_execute_API.c:866
#10 0x0000000000672dd9 in zim_reflection_method_invoke (execute_data=<value optimized out>, return_value=0x7f24cdc163f0) at /root/source/php-7.0.7/ext/reflection/php_reflection.c:3234
#11 0x000000000087eef8 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f24cdc162c0) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:842
#12 0x0000000000846e70 in execute_ex (ex=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:417
#13 0x0000000000899f2b in zend_execute (op_array=0x7f24cdc6d000, return_value=<value optimized out>) at /root/source/php-7.0.7/Zend/zend_vm_execute.h:458
#14 0x0000000000807603 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/source/php-7.0.7/Zend/zend.c:1427
#15 0x00000000007a9de0 in php_execute_script (primary_file=0x7fff5e3f4180) at /root/source/php-7.0.7/main/main.c:2494
#16 0x00000000008a7dbe in main (argc=<value optimized out>, argv=<value optimized out>) at /root/source/php-7.0.7/sapi/fpm/fpm/fpm_main.c:1968
(gdb) zbacktrace 
[0x7f24cdc16b30] RedisCluster->get("t1324575") [internal function]
```

**Comment by yatsukhnenko** [comment]
Thanks, @zhuleilei. But now I have no idea how this bug may happens 😵

**Comment by michael-grunder** [comment]
@yatsukhnenko Possibly related to `convert_to_*` type calls?  This can make the zend heap go all wonky in php7.

I actually used this under php < 7.0 for a long time before realizing that it can cause problems there too, although not usually a segfault.  Perhaps I can get lucky and cause the segfault locally.  :smile:

**Comment by yatsukhnenko** [comment]
@michael-grunder, thanks for the advice!

**Comment by zhuleilei** [comment]
Thanks all guys. And how to fix this problem? Need more infomation of my envirment? Or more backtrace?

**Comment by yatsukhnenko** [comment]
@zhuleilei, I pushed some changes. Test please.

**Comment by yatsukhnenko** [comment]
@michael-grunder, I removed almost all calls of convert_to_* functions. I hope this will decrease numbers of segfaults

**Comment by zhuleilei** [comment]
not fixed yet, backtraces are as same as  https://github.com/phpredis/phpredis/issues/1036#issuecomment-264062265

**Comment by yatsukhnenko** [comment]
@zhuleilei, how can I reproduce this? Do you have a script?

**Comment by zhuleilei** [comment]
coredump show up randomly。 

```php
<?php
$rediscluster = new RedisCluster(......);
$rediscluster->get("t1324575");
```

**Comment by yatsukhnenko** [comment]
@zhuleilei, did you try the latest version of phpredis?

**Comment by yatsukhnenko** [comment]
@zhuleilei version 3.1.4RC1 is up on PECL site. Could you try to reproduce your crash with it?

**Comment by yatsukhnenko** [comment]
3.1.4 has been released on PECL site. Open new issue if crash will reproduce
