### ISSUE TITLE
for json includes... configure: error: Cannot find php_json.h

### ISSUE THREAD

**Issue by chomyeong** [phpredis/phpredis#1745]
os:mac
php:7.3
I try run "pecl install redis"
but,i get the error message:
for json includes... configure: error: Cannot find php_json.h
everyone has this one question?

**Comment by bonzaphp** [comment]
me too

**Comment by TroodoNmike** [comment]
same

**Comment by yatsukhnenko** [comment]
You need to install `json` extension. I don't know how to do this on mac, may be @michael-grunder will help?

**Comment by mi-nakano** [comment]
I have the same problem.
And make minimum PR #1763

**Comment by yatsukhnenko** [comment]
@mi-nakano thanks, merged

**Comment by michael-grunder** [comment]
Looks like this is fixed, closing.

**Comment by willsmanley** [comment]
What was the fix for this? I am still getting the php_json.h error...

**Comment by yatsukhnenko** [comment]
@willsmanley the fix was in PR #1763

**Comment by bharatiadkar** [comment]
I am still see the error
configure: error: Cannot find php_json.h

**Comment by MvanRietschoten** [comment]
I am also getting this error
```
pecl install redis
downloading redis-5.2.2.tgz
...
checking for json includes... configure: error: Cannot find php_json.h
```

**Comment by yatsukhnenko** [comment]
The fix is in upcoming 5.3.0 release

**Comment by simonxmau** [comment]
Me too! I am installing on the redis-5.3.0.tgz version and the problem remains the same.

**Comment by michael-grunder** [comment]
Perhaps you don't have `php_json.h`?

Can you post the entire output from `config.log`?

**Comment by simonxmau** [comment]
@michael-grunder 

```
sudo pecl install redis
Password:
downloading redis-5.3.0.tgz ...
Starting to download redis-5.3.0.tgz (264,024 bytes)
......................................................done: 264,024 bytes
29 source files, building
running: phpize
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
enable igbinary serializer support? [no] :
enable lzf compression support? [no] :
enable zstd compression support? [no] :
building in /private/tmp/pear/install/pear-build-rootlE7VDr/redis-5.3.0
running: /private/tmp/pear/install/redis/configure --with-php-config=/usr/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin19.5.0
checking host system type... x86_64-apple-darwin19.5.0
checking target system type... x86_64-apple-darwin19.5.0
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-non-zts-20180731
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable redis support... yes, shared
checking whether to disable sessions... yes
checking whether to disable json serializer support... yes
checking whether to enable igbinary serializer support... no
checking whether to enable msgpack serializer support... no
checking whether to enable lzf compression... no
checking use system liblzf... no
checking whether to enable Zstd compression... no
checking use system libsztd... yes
checking whether to enable lz4 compression... no
checking use system liblz4... no
checking for json includes... configure: error: Cannot find php_json.h
ERROR: `/private/tmp/pear/install/redis/configure --with-php-config=/usr/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no' failed
```

**Comment by michael-grunder** [comment]
This seems relevant:

```
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
```

It's been ages since I've installed with PECL but I think you're missing the version path

e.g. my `php_json.h` is here:

```/usr/include/php/20190902/ext/json/php_json.h```

My [config.log](https://gist.github.com/michael-grunder/cc02ec3cc74552fab6cf76bc7f36e9c9) differs in that it finds the correct version subdirectory.

**Comment by simonxmau** [comment]
@michael-grunder Thank you.
