### ISSUE TITLE
Add username support for auth in rediscluster handler

### ISSUE THREAD

**Issue by lencell** [phpredis/phpredis#1879]
Hi, 

this is more of a feature/improvement request than a bug report, i was wondering if it would be possible to add username support in the rediscluster session handler(https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#sessionsave_path the "auth" parameter) in the same way that it is supported for the redis session handler(https://github.com/phpredis/phpredis#php-session-handler the "auth" parameter as well) , thus allowing to connect to a rediscluster while taking advantages of ACL that have been introduced since version 6 of redis

### Expected behaviour
With the following in php.ini:

> session.save_handler = rediscluster
session.save_path = "seed[]=host1:6379&seed[]=host2:6379&auth[]=**username**&auth[]=**password**"

Authenticating as user **username** with password **password**

### Actual behaviour
As of now we get an error that phpredis could not map key clusterspace with any of the provided seeds (which is hiding the failure to authenticate too, better error reporting on authentication errors would be nice as well)

### I'm seeing this behaviour on
- OS: Ubuntu 18 LTS
- Redis: 6.0.9
- PHP: 7.2
- phpredis: 5.3.2

### I've checked
- [X] There is no similar issue from other users
- [] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment]
It should not be difficult, I'll try to look on it this weekend

**Comment by yatsukhnenko** [comment]
@lencell it looks like we've already added it to 5.3.2 https://github.com/phpredis/phpredis/blob/develop/redis_session.c#L892

**Comment by lencell** [comment]
Thank you for your answer, it's weird because I'm pretty sure I tried with 5.3.2 and had the issue, if it's ok with you I will check my php redis version and reproduce it again and send you more information, could you confirm I'm using the right syntax for it and that I'm not just doing it wrong ?
> session.save_path = "seed[]=host1:6379&seed[]=host2:6379&auth[]=username&auth[]=password"

**Comment by yatsukhnenko** [comment]
session.save_path looks good, you can also try to use `auth[username]=username&auth[password]=password`

**Comment by lencell** [comment]
Ok thanks to your answers I fixed what i had wrong, I just tried again, it worked with
> session.save_path = "seed[]=host1:6379&seed[]=host2:6379&auth[]=username&auth[]=password"

If it can help anyone else not make the same mistake as me I guess you could put in the documentation that the user should have access to the "cluster" command or else it will not be able to map the clusterspace (I know it seems obvious now...), especially if you're like me and you for example removed the @admin group of commands in your ACL rules.

Thanks a lot for your time, I'm closing this issue now.
Best regards.

**Comment by 13ilya-old** [comment]
Please add the correct examples to the https://github.com/phpredis/phpredis/blob/develop/README.markdown#php-session-handler .
I still don't understand what to specify auth for **php session handler** there.
**user**=USER&**pass**=PASSWORD or **username**=USER&**password**=PASSWORD or **auth**=USER&**auth**=PASSWORD or something else.

P.S. Also, what does the **timeout** parameter mean?
The same as timeout in the config or is it the maximum time the server waits for a response when connecting (in case the server is busy or unavailable)?
If the latter, what is the default timeout?

**Comment by 13ilya-old** [comment]
> auth[username]=username&auth[password]=password

**auth[user]**=USER&**auth[pass]**=PASSWORD Is only correct variant!
