### ISSUE TITLE
Redis scan cursor returns unsigned int, conversion to signed int causes incorrect cursor on following iteration.

### ISSUE THREAD

**Issue by mikemoranmurj** [phpredis/phpredis#2454]
### Expected behaviour
When running a redis scan command, I expect the iterator to be the same value as the redis cursor.
### Actual behaviour
The cursor is being converted to a signed int, while redis returns an unsigned int. So any cursor over the signed int max value is set to the signed int max value before the next scan iteration.

### I'm seeing this behaviour on
-OS: Linux
- Redis: 8.1
- PHP: 8.2
- phpredis: 6.0.2

### Steps to reproduce, backtrace or example script
When redis scan command returns a cursor larger than the signed int max value,
$iter will be 9223372036854775807, which is sent to redis for the next iteration.
```
do {
  $arr_keys = $redis->scan($iter, $server, $pattern, $count);
      if($arr_keys !== FALSE){
          foreach($arr_keys as $str_key){
              echo "key";
          }
      }
  echo $iter;
}
while($iter > 0);
```
This is using RedisCluster with a targeted node in the scan parameters

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment]
Are you actually seeing cursors that large?  To my knowledge, you are the first person to encounter this.

This is a bug, although one that might be a bit tricky to fix given that PHP's `int` representation is signed.  There is no userland `unsigned 64 bit int` in PHP.

**Comment by mikemoranmurj** [comment]
Yeah, I am seeing cursors that large.

From the docs,  [https://redis.io/commands/scan/](https://redis.io/commands/scan/) redis returns a string representation of the unsigned int as its first element. Why not preserve the return type?

**Comment by michael-grunder** [comment]
I'm genuinely curious how you're seeing them that large.  The cursor is a function of the hash table's size mask, which is always 2^n-1.

Maybe they show up that large on big-endian machines?  What hardware are you using and how large is your database?

> From the docs, https://redis.io/commands/scan/ redis returns a string representation of the unsigned int as its first element. Why not preserve the return type?

This is what I'll do.  I didn't mean that the problem was unsolvable only that PHP presents a specific issue in this case, due to how it works internally.

**Comment by mikemoranmurj** [comment]
The database is relatively small, and I'm not certain why the cursor is so large. This occurred after migrating to a serverless cache on AWS. The same database on a provisioned cache returns a more typical cursor value.

**Comment by michael-grunder** [comment]
This should be fixed in 2e37f5b.  The change essentially splits how we represent cursors in our reference argument such that values `<= ZEND_LONG_MAX` continue to be represented as integers.

If the cursor is too large, however, they are stored as strings.  I think the way I did the update minimizes breakage, since the common idiom of looping until the curosr is again zero will still work:

```php
$it = NULL;
do {
    $keys = $redis->scan($it);
    do_stuff_with_keys($keys);
} while ($it !== 0);
```

Before I open a PR with the change, I will verify the branch's behavior in a virtualized 32-bit PHP container.

Since I have no idea how to get Redis to issue such large cursors I tested this locally by creating a fake Redis server that generated mock SCAN replies with very large cursor values.  Integrating this into our test suite might be worth it, but that's also quite a few new moving parts for such a small edge case.

**Comment by michael-grunder** [comment]
I realized we need to add similar logic for the `RedisCluster` class.  It looks to work and I will merge those changes tomorrow.

**Comment by michael-grunder** [comment]
Fixed in #2458 and #2462

**Comment by ps-20x** [comment]
I am currently running into this issue still. My cursor is unfortunately also very large (`13956817222759301142`). I am using `scan` and connect to my vercel KV store (not a cluster). The first request with cursor `null` works and the second request with a cursor `278649085879408013` works as well. But the third cursor is `13956817222759301142`. Starting from there I am getting into a loop and always get the big cursor returned. I am not sure how to provide a reproduction there though

The redis version is `6.2.6` and my phpredis version is `6.1.0`

**Comment by michael-grunder** [comment]
Do you mean that the cursor never returns to zero? The change we made for `6.1.0` is to support very large cursors by treating them as a string.

1. How large is the Redis database
2. What architecture

If you can reproduce this in a container I'm sure the fix would be trivial. I'll double-check the logic in cluster but without being able to actually get these large cursor values I'm not really able to test in a realistic way.

**Comment by ps-20x** [comment]
Thank you very much for getting back to me and helping me there. Yes, exactly. So the cursor gets stuck at the very large number and it never gets updated again. So the first response is a cursor with let's say 3 keys. The next response is the large cursor with another 5 keys and then I am getting again the same response with 5 keys and the large cursor very often (I have a manual loop stopper now after 10 tries).
So, how this blows up like this is that we are caching requests with nuxt in our vercel redis. Unfortunately those keys are never removed (so far - currently trying to fix it but got stuck with the long cursors). So the redis-cache builds up over time. At the moment the total keys are `total_keys:79573` (but I removed already a few tens of thousands)
So the frontend architecture is Nuxt (JS) with Vercel connected KV store (redis)
Now I try to add logic for updating those keys and removing old ones in our backend which is Laravel (PHP)

**Comment by michael-grunder** [comment]
Ok. Getting stuck on the same cursor is a clue. I'll try to replicate this when I'm back at my desk. 

By architecture I mean as in x86-64, ARM, Sparc, etc.

I've never been able to replicate the large cursor values in Redis and I'm kind of just curious how I could.

**Comment by michael-grunder** [comment]
Unfortunately I can't replicate this. I've never been able to get Redis to return these large cursor values, but I did write a fake redis server to force them, but PhpRedis handles them perfectly.

```php
<?php

$rc = new RedisCluster(NULL, ['127.0.0.1:7000']);

$it = NULL;

while (($keys = $rc->scan($it, 'foo')) !== false) {
    $dit = var_export($it, true);
    printf("Cursor: %s\n", $dit);
    print_r($keys);
}
```

And the output:

```
 sapi/cli/php scan.php
Cursor: 1
Array
(
    [0] => string:60
    [1] => string:20
    [2] => string:21
    [3] => string:20
    [4] => string:59
    [5] => string:86
    [6] => string:46
    [7] => string:37
    [8] => string:64
    [9] => string:37
)
Cursor: 4294967295
Array
(
    [0] => string:24
    [1] => string:3
    [2] => string:28
    [3] => string:64
    [4] => string:95
    [5] => string:60
    [6] => string:64
    [7] => string:7
    [8] => string:77
    [9] => string:36
)
Cursor: 9223372036854775807
Array
(
    [0] => string:59
    [1] => string:15
    [2] => string:32
    [3] => string:33
    [4] => string:55
    [5] => string:33
    [6] => string:55
    [7] => string:64
    [8] => string:91
    [9] => string:19
)
Cursor: '9223372036854775809'
Array
(
    [0] => string:25
    [1] => string:42
    [2] => string:32
    [3] => string:68
    [4] => string:24
    [5] => string:29
    [6] => string:64
    [7] => string:82
    [8] => string:19
    [9] => string:15
)
Cursor: '18446744073709551615'
Array
(
    [0] => string:33
    [1] => string:86
    [2] => string:29
    [3] => string:60
    [4] => string:99
    [5] => string:25
    [6] => string:25
    [7] => string:64
    [8] => string:55
    [9] => string:25
)
Cursor: 0
Array
(
    [0] => string:95
    [1] => string:95
    [2] => string:51
    [3] => string:55
    [4] => string:82
    [5] => string:32
    [6] => string:77
    [7] => string:19
    [8] => string:21
    [9] => string:33
)
```

I made sure that the fake server hit all the edge cases, so small to large as well as large to small. You can see PhpRedis either returning a numeric cursor or a string if the value is > 2^63.

Happy to help further but we may need a replicator to fix it.

**Comment by ps-20x** [comment]
> Unfortunately I can't replicate this. I've never been able to get Redis to return these large cursor values, but I did write a fake redis server to force them, but PhpRedis handles them perfectly.

Thank you very much for looking into it. One difference I noticed was that you instantiate a `RedisCluster`. Do you think that this can make a difference?

I have created an empty laravel project with docker containers to have a quick project setup:
https://github.com/ps-20x/redis-cursor-issue

I have added some information in the [README.md](https://github.com/ps-20x/redis-cursor-issue/blob/main/README.md) for starting and stopping the project and how to test the redis cursor issue for us.

If you want I can provide you with a read-only access token to our vercel redis if that would help you?

**Comment by michael-grunder** [comment]
@ps-20x Should be fixed in [7f17c16](https://github.com/phpredis/phpredis/commit/7f17c1608ae6e6a2e9d3b5e9e3bdb9b5ee95c86f).

The problem wsa casting a `uint64_t` to a `long` when building the command which can cause an overflow. Redis on the other hand assumes an unsigned cursor so it converts the negative value to an `uint64_t` and we enter an infinite loop.

```
127.0.0.1:6379> scan -5
1) "711"
2)  1) "string:371"
    2) "string:381"
    3) "string:543"
    4) "string:203"
    5) "string:437"
    6) "string:720"
    7) "string:275"
    8) "string:985"
    9) "string:88"
   10) "string:386"
127.0.0.1:6379> scan -5
1) "711"
2)  1) "string:371"
    2) "string:381"
    3) "string:543"
    4) "string:203"
    5) "string:437"
    6) "string:720"
    7) "string:275"
    8) "string:985"
    9) "string:88"
   10) "string:386"
```

**Comment by ps-20x** [comment]
@michael-grunder thank you very much for looking into it and fixing it. I appreciate it.

Do you have any estimation on when the next release will be?

**Comment by michael-grunder** [comment]
No specific timeframe but we should do it soon. There are a few fixes since 6.1.0

**Comment by ps-20x** [comment]
> No specific timeframe but we should do it soon. There are a few fixes since 6.1.0

@michael-grunder Sorry to bother again. Is there anything blocking a release at the moment? Anything where I could support you?

**Comment by michael-grunder** [comment]
We should put together a release soon. I'll shoot for sometime next week.
