### ISSUE TITLE
protocol error, got 'n' as reply type byte

### ISSUE THREAD

**Issue by acasademont** [phpredis/phpredis#831]
Just updated to Redis 3.2.0 and the new phpredis 3.0.0 and randomly I get this error. Any ideas? Downgrading redis server to 3.0.7 seems to fix the problem

**Comment by michael-grunder** [comment]
Do you happen to have a snippet of code that causes this that I could test?

**Comment by tunh** [comment]
I have the same problem with Redis 3.1, downgrade to 3.0 & 2.8 work perfectly!
I use Redis as session storage with get/set method.

**Comment by vingrad** [comment]
I have the same problem.

**Comment by acasademont** [comment]
Hi @michael-grunder, this is something deep in the Redis bundle and with Symfony sessions, it will be hard to provide a snippet of it. Do you have any insights of what might have triggered that change from 3.0.x to 3.2.x?

**Comment by michael-grunder** [comment]
I'm not sure to be honest.  I have 3.2.0 locally so I will do some more digging.

**Comment by vingrad** [comment]
With the new Redis 3.2.1 is the same problem:
RedisException: protocol error, got 'n' as reply type byte

**Comment by vingrad** [comment]
I think that I found the solution of this problem. You need to set this in redis.conf:
protected-mode no

**Comment by acasademont** [comment]
interesting, is this a new setting?

**Comment by acasademont** [comment]
definitiely this is the cause, if protected mode is activated (and it is under a number of circumstances starting Redis 3.2) the connection will fail.

**Comment by michael-grunder** [comment]
Yeah, I wonder if it has to do with the error message which is about as long as a short novel :smiley_cat:

I will try to replicate it so phpredis can pass the message forward to the caller.

Cheers!
Mike

**Comment by yeyu79520** [comment]
I also met ，now  we can open redis.conf  ，We look at his configuration，Do it in this way.
# bind 127.0.0.1 
daemonize no
protected-mode no   ：：：： This is the most important
now  we can redis-server redis.conf 
Hope to help you

**Comment by yatsukhnenko** [comment]
Resolved

**Comment by 719media** [comment]
Question, how is this resolved? I am running the latest redis version from AWS (Redis 3.2.10) and using the latest phpredis (3.1.4) in my load-balanced environment and I still get this error. I get it from time to time on a single server (while other servers continue to operate normally), and the issue is fixed by `service php-fpm restart`.

```
[2017-11-26 01:08:29] app.CRITICAL: RedisException: protocol error, got 'K' as reply type byte
[2017-11-26 01:08:31] app.CRITICAL: RedisException: protocol error, got '?' as reply type byte
[2017-11-26 01:08:32] app.CRITICAL: RedisException: protocol error, got '' as reply type byte
```

these errors are from various lines in the code where I am connecting to redis, to it appears to be a problem most likely with pconnect(), (since once it goes "bad" for a single server, everything goes bad)

**Comment by yatsukhnenko** [comment]
@719media `protected-mode no` option fixed the problem. If you have a similar problem and steps to reproduce it you always may to open new issue

**Comment by 719media** [comment]
Unfortunately I don't have access to change that parameter in AWS from what I can tell. I ended up just using connect() instead of pconnect() to address the issue.
I wish I could reproduce the problem with a test case, I would happily provide one.
Thank you for your time.

**Comment by camry** [comment]
I have the same problem.

**Comment by camry** [comment]
@yatsukhnenko `protected-mode no` is not ok. 

```
2018-01-23 02:43:30.052 [ERROR][#2924] protocol error, got 'g' as reply type byte
2018-01-23 02:44:06.816 [ERROR][#2924] protocol error, got 'i' as reply type byte
```

**Comment by yatsukhnenko** [comment]
@camry how to reproduce the issue?

**Comment by zhenhai1** [comment]
I have same problem,

**Comment by camry** [comment]
@yatsukhnenko  I have solved. Is the issue of sticky package.

**Comment by tomponline** [comment]
We are seeing something similar with phpredis 4.1.1 and redis 3.2.0

https://github.com/phpredis/phpredis/issues/1389

Its not protected mode, as most of the time its working fine.

**Comment by theOtherNir** [comment]
It's an old post but without a concrete answer so maybe this will help someone.
I had the same issue, I've mistakenly pointed the REDIS client to connect to the wrong port (MySql in my case)
important to note that the port is actually listening.
therefore it looks like a failure in the protocol and not a failure to connect.

**Comment by guiajlopes** [comment]
I also have this issue and it's really hard to debug, It's really rare but I get those every day using redis server 3.2 and phpredis 5.3.3. Getting them mainly on PING here is the error message `protocol error, got '7' as reply-type byte`

Tried to use `protected-mode no` and it did not help, also switched from pconnect to only connect and I still get them

**Comment by donng** [comment]
Issue is closed, so is there a conclusion ?

**Comment by donng** [comment]
> @yatsukhnenko I have solved. Is the issue of sticky package.

How did you fix it ...

**Comment by amfriedman** [comment]
I have the same issue. Just started suddenly today, out of the blue.

PHP 7.2.24
Redis Server 4.0.9
php-redis 3.1.6
